### ISSUE TITLE
calling googleearthplot

### ISSUE THREAD

**Issue by creaturerigger** [AtsushiSakai/googleearthplot#1]
Hello, this is the code same as in the documentation
`
from googleearthplot import googleearthplot
aa = googleearthplot()
`
and it raises an error: 

`Traceback (most recent call last):
  File "C:/Users/PC/Documents/pyProjects/firstProject/plot01deneme.py", line 4, in <module>
    aa = googleearthplot()
TypeError: 'module' object is not callable`

Thank you.

**Comment by creaturerigger** [comment]
`from googleearthplot.googleearthplot import googleearthplot`

this solved the problem thank you.

**Comment by AtsushiSakai** [comment]
Thank you for feedback : ).
You are right, it is my mistake.
I updated the documents.

I hope you enjoy the library : ).

**Comment by creaturerigger** [comment]
I really did. Thank you for your effort I am thankful to you. 💯 💯 👍 🥇  Btw there is a problem with csv file sample link I think. I will try to create a csv file with referencing variables in PlotBarChartsFromCSV method, I hope it will work. :)

**Comment by AtsushiSakai** [comment]
I think it will work if you set a full path of a csv file for PlotBarChartsFromCSV.
It doesn't work?
As you can see in the PlotBarChartsFromCSV code, the filepath is just a string variable and it is just input of pandas.read_csv. 
If you have any question, feel free to ask me : ).

**Comment by creaturerigger** [comment]
Ok thank you very much :) it 💯% worked thanks a lot. 👍 👍 👍
